# Generated by Django 5.2.9 on 2026-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='content',
            field=models.TextField(),
        ),
    ]
