# Generated by Django 5.2.9 on 2026-01-22 07:16

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_questioncategory_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='blog.questioncategory'),
        ),
    ]
