# Generated by Django 5.2.9 on 2026-01-22 07:51

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_question_embedding_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
